# Generated by Django 3.2 on 2023-10-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_auto_20231001_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='last_search_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
